//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minutrade.ECommerce.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Phones = new HashSet<Phone>();
        }
    
        public long Id { get; set; }
        public Nullable<long> MaritalStatusId { get; set; }
        public long StateId { get; set; }
        public string Cpf { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Street { get; set; }
        public string Neighborhood { get; set; }
        public int Number { get; set; }
        public string CEP { get; set; }
        public string Complement { get; set; }
        public string ReferenceInformation { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<Phone> Phones { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
    }
}
