//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minutrade.ECommerce.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public long id { get; set; }
        public Nullable<long> ClientId { get; set; }
        public short CodArea { get; set; }
        public string Number { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
